name: 'FHIR CapabilityStatement Expander'
description: 'Expands FHIR CapabilityStatements by recursively resolving imports and extracts all refer        echo ""
        echo "📁 Copied Resources:"
        
        # Then show all other files (copied) - search recursively including subdirectories
        while IFS= read -r -d '' file; do resources'
author: 'Patrick Werner'

branding:
  icon: 'layers'
  color: 'blue'

inputs:
  input_directory:
    description: 'Path to input directory with FHIR JSON files'
    required: true
    default: './input'
  output_directory:
    description: 'Path to output directory for expanded resources'
    required: true
    default: './output'
  capability_statement_url:
    description: 'Canonical URL(s) of the CapabilityStatement(s) to expand. Can be a single URL string or a JSON array of URLs (use toJSON() for YAML lists).'
    required: true
  verbose:
    description: 'Enable verbose logging'
    required: false
    default: 'false'
  python_version:
    description: 'Python version for execution'
    required: false
    default: '3.11'

outputs:
  expanded_files_count:
    description: 'Number of created expanded files'
    value: ${{ steps.expand.outputs.files_count }}
  output_directory:
    description: 'Path to output directory with expanded resources'
    value: ${{ inputs.output_directory }}
  expanded_capability_statement:
    description: 'Filename of the expanded CapabilityStatement'
    value: ${{ steps.expand.outputs.expanded_file }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
               
    - name: Validate Input Directory
      shell: bash
      run: |
        if [ ! -d "${{ inputs.input_directory }}" ]; then
          echo "❌ Input directory not found: ${{ inputs.input_directory }}"
          exit 1
        fi
        
        json_files=$(find "${{ inputs.input_directory }}" -name "*.json" | wc -l)
        echo "✅ Input directory found with $json_files JSON files"
        
        if [ "$json_files" -eq 0 ]; then
          echo "⚠️  Warning: No JSON files found in input directory"
        fi
        
    - name: Create Output Directory
      shell: bash
      run: |
        mkdir -p "${{ inputs.output_directory }}"
        echo "📁 Output directory created: ${{ inputs.output_directory }}"
        
    - name: Run FHIR CapabilityStatement Expander
      id: expand
      shell: bash
      run: |
        # Determine verbose flag - auto-enable when GitHub Actions debug logging is active
        VERBOSE_FLAG=""
        if [ "${{ inputs.verbose }}" = "true" ] || [ "$ACTIONS_STEP_DEBUG" = "true" ]; then
          VERBOSE_FLAG="--verbose"
          if [ "$ACTIONS_STEP_DEBUG" = "true" ]; then
            echo "🔍 Auto-enabled verbose logging (GitHub Actions debug mode detected)"
          fi
        fi
        
        # Run the expander
        # Use the environment variable for container compatibility
        SCRIPT_PATH="$GITHUB_ACTION_PATH/capability_statement_expander.py"
        
        if [ -f "$SCRIPT_PATH" ]; then
          echo "✅ Script found, executing..."
          
          # Write capability_statement_url to temporary file to avoid "Argument list too long" error
          # This handles cases with many CapabilityStatements where JSON becomes very large
          CS_URLS_FILE=$(mktemp)
          echo '${{ inputs.capability_statement_url }}' > "$CS_URLS_FILE"
          
          # Run the expander
          python "$SCRIPT_PATH" \
            "${{ inputs.input_directory }}" \
            "${{ inputs.output_directory }}" \
            "@$CS_URLS_FILE" \
            ${{ inputs.verbose == 'true' && '--verbose' || '' }}
          
          # Clean up temporary file
          rm -f "$CS_URLS_FILE"
          
          echo "$EXPANDER_OUTPUT"
          
          # Extract number of copied files from log output
          copied_files=$(echo "$EXPANDER_OUTPUT" | grep -o '[0-9]\+ files copied' | grep -o '[0-9]\+' || echo "0")
          files_count=$copied_files
          
          echo "files_count=$files_count" >> $GITHUB_OUTPUT
          
          # Find expanded CapabilityStatement file
          expanded_file=$(find "${{ inputs.output_directory }}" -name "*expanded.json" | head -1 | xargs basename 2>/dev/null || echo "")
          echo "expanded_file=$expanded_file" >> $GITHUB_OUTPUT
          
          echo "✅ Capability Statement successfully expanded to ${{ inputs.output_directory }}"
          echo "✅ Successfully processed $files_count files"
        else
          echo "❌ Script not found at expected location: $SCRIPT_PATH"
          echo "Action path: ${{ github.action_path }}"
          echo "Environment path: $GITHUB_ACTION_PATH"
          exit 1
        fi
        
    - name: List Processed Files
      shell: bash
      run: |
        # Read the JSON summary file created by the expander
        SUMMARY_FILE="${{ inputs.output_directory }}/.fhir-processing-summary.json"
        
        if [ -f "$SUMMARY_FILE" ]; then
          echo "📄 Processed FHIR Resources:"
          echo "================================"
          
          # Parse totals using simple grep from the file
          expanded_count=$(grep -o '"total_expanded": [0-9]*' "$SUMMARY_FILE" | grep -o '[0-9]*' || echo "0")
          copied_count=$(grep -o '"total_copied": [0-9]*' "$SUMMARY_FILE" | grep -o '[0-9]*' || echo "0")
          total_files=$(grep -o '"total_files": [0-9]*' "$SUMMARY_FILE" | grep -o '[0-9]*' || echo "0")
          
          echo "🔧 Expanded Resources:"
          if [ "$expanded_count" -gt 0 ]; then
            # Extract relative_path from expanded_files section
            sed -n '/"expanded_files"/,/"copied_files"/p' "$SUMMARY_FILE" | \
            grep '"relative_path"' | \
            sed 's/.*"relative_path": *"\([^"]*\)".*/  📋 \1/' | \
            while read -r line; do
              echo "$line (expanded)"
            done
          else
            echo "  (No expanded resources found)"
          fi
          
          echo ""
          echo "📁 Copied Resources:"
          if [ "$copied_count" -gt 0 ]; then
            # Extract from copied_files section - use line-by-line processing
            sed -n '/"copied_files"/,/"total_expanded"/p' "$SUMMARY_FILE" | \
            grep -E '"relative_path"|"resource_type"' | \
            paste - - | \
            sed 's/.*"relative_path": *"\([^"]*\)".*"resource_type": *"\([^"]*\)".*/  📋 \1 [\2]/' || {
              # Simple fallback
              grep '"relative_path"' "$SUMMARY_FILE" | tail -n +2 | \
              sed 's/.*"relative_path": *"\([^"]*\)".*/  📋 \1/'
            }
          else
            echo "  (No copied resources found)"
          fi
          
          echo "📊 Summary:"
          echo "  🔧 Expanded: $expanded_count files"
          echo "  📁 Copied: $copied_count files"
          echo "  📋 Total: $total_files files processed"
        else
          echo "⚠️  Processing summary file not found: $SUMMARY_FILE"
        fi
